### PR TITLE
Nat network support

### PR DESCRIPTION
**Pull request by isage**
Add support for virtualbox nat networks as a resource and natnetwork type for NICs
E.g.:
```
resource "virtualbox_natnetwork" "vmnet10" {
    name = "vmnet10"
    dhcp = true
    network = "192.168.6.0/24"
}

resource "virtualbox_vm" "squid" {
  count     = 2
  name      = format("node%02d", count.index + 1)
  image     = "virtualbox.box"
  cpus      = 1
  memory    = "256 mib"

  network_adapter {
    type           = "hostonly"
    host_interface = "vboxnet0"
  }

  network_adapter {
    type           = "natnetwork"
    nat_network    = virtualbox_natnetwork.vmnet10.name
  }
}

```

Requires https://github.com/terra-farm/go-virtualbox/pull/13

### CODE REVIEW

**Comment by VoyTechnology** [comment]
Please take a look at the failing CI @isage.

**Comment by isage** [comment]
It states right there in description that it *requires* terra-farm/go-virtualbox#13 of course it will fail otherwise.

**Comment by VoyTechnology** [comment]
Sorry, I missed that.

**Comment by nevill** [comment]
I just compiled the code (of course with terra-farm/go-virtualbox#13) and everything works well.

The thing is, in NAT Network, we cannot connect to the VM directly. But, usually terraform provisioners require a network connection to control it. Is there any work-around? Like providing a port forward resource and using it as connection?

**Comment by isage** [comment]
I'm not sure of usage cases (i was contracted to implement nat network
support), but yeah, nat network supports port forwarding, so it should be
doable ( in separate pull request)

**Comment by patsevanton** [comment]
I think need use NAT Network with Host-only Network.

**Comment by nevill** [comment]
> I think need use NAT Network with Host-only Network.

@patsevanton In this case, `Host-only` + `NAT` is working and preferred. Because it doesn't need to create a NAT Network.

**Comment by patsevanton** [comment]
@nevill No

https://github.com/terra-farm/terraform-provider-virtualbox/issues/75

**Comment by nevill** [comment]
> @nevill NAT interface have **equal** IP address on all virtualbox machine
> 
> #75
> 
> Host-only + NAT Network have **different** IP address on all virtualbox machine

Yes, I understand the difference. `Host-only` NIC can have different IPs. In this way, they're equivalent, but NAT Network has one more resource to create.

I'd like to use NAT Network if the connection problem mentioned above gets resolved.

**Comment by patsevanton** [comment]
Hello! may be merge PR?

**Comment by jpts** [comment]
Hi folks, I'm interested in getting this functionality merged in (in addition to the [go library PR](/terra-farm/go-virtualbox/pull/13)). Is there anything else that needs to be done for this, except for rebasing and resolving conflicts? 

@isage are you still interested in picking this up, or should I create a new PR to pickup the work in?

**Comment by isage** [comment]
I'm not interested, so go ahead. Same goes for go-virtualbox.

**Comment by VoyTechnology** [comment]
Closing in favour of #103.

**Pull request closed without merging**
