### PR TITLE
Update examples, to describe how to make it working, see #34

### PR DESCRIPTION
**Pull request by nevill**
see #34 for details.

### CODE REVIEW

**Comment by VoyTechnology** [comment]
Please keep in mind #40.

**Comment by nevill** [comment]
Great @VoyTechnology , once your PR merged, this one can be closed.
Still, I'd suggest adding something about guest addition in README.

**Comment by VoyTechnology** [comment]
@nevill Can you please rebase please? I think the `host_interface` is the main change in this PR after rebasing.

**Comment by nevill** [comment]
@VoyTechnology done

**Pull request merged**
