### PR TITLE
Add Requirements

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by ringods** [comment]
Please migrate these instructions to the docs. They will get published to the website then.

**Comment by patsevanton** [comment]
Here https://github.com/terra-farm/terra-farm.github.io/blob/site/modules/ROOT/pages/installation.adoc ? I cannot find.

**Comment by ringods** [comment]
No, this provider has its own set of docs in the `modules` folder. Please add the Requirements in the main page here:

https://github.com/terra-farm/terraform-provider-virtualbox/blob/master/modules/ROOT/pages/index.adoc

**Comment by patsevanton** [comment]
https://github.com/terra-farm/terraform-provider-virtualbox/pull/71

**Pull request closed without merging**
